### ISSUE TITLE
Depth data is being clamped at ~4m

### ISSUE THREAD

**Issue by bgstaal** [microsoftarchive/KinectCommonBridge#9]
I'm experiencing this through the ofxCommonBridge add-on for openFrameworks but I suspect it's clamped at an earlier level. In contrast to when using the libfreenect based ofxKinect add-on it seams impossible to read any depth values beyond 4 meters.

**Comment by mkostin** [comment]
Clamping takes place at the driver level to maintain a consistent level of quality in the depth and skeleton tracking. You can see [related discussion](http://social.msdn.microsoft.com/Forums/en-US/1e663e55-5169-4fea-9ad6-3212a8ae36c5/is-the-maximum-depth-really-4m?forum=kinectsdknuiapi) on that matter. Framework has nothing to do with it since that level of functionality would have to come at the technology level not the wrapper. 

> The Kinect depth sensor range is: minimum 800mm and maximum 4000mm. The Kinect for Windows Hardware can however be switched to Near Mode which provides a range of 500mm to 3000mm instead of the Default range. 
> -- <cite>[msdn.microsoft.com](http://msdn.microsoft.com/en-us/library/hh438998.aspx)</cite>

To access that data you would have to use 3-d party device driver. But please note that error rate beyond the [announced limits ](http://blogs.msdn.com/b/kinectforwindows/archive/2012/01/20/near-mode-what-it-is-and-isn-t.aspx) makes data not really accurate and not reliable.

**Comment by mkostin** [comment]
Closing.

**Comment by bgstaal** [comment]
According to this: http://social.msdn.microsoft.com/Forums/en-US/6dbaa791-bb37-4de2-96ff-eeda61df2c12/raw-unaltered-depth-data-from-the-kinect-possible-with-ms-kinect-sdk?forum=kinectsdknuiapi and this:  & this: http://msdn.microsoft.com/en-us/library/microsoft.kinect.depthimageframe.maxdepth.aspx full depth has been available since SDK v.1.6. At least in the C# version of the API. I can't seem to find the C++ equivalent of that function though, but it at least proves that it is not clipped on the driver level.

**Comment by bgstaal** [comment]
Well, after some research I found out that KCB actually supports access to the extended depth data through the method `KinectGetDepthImagePixels` witch returns an array of `NUI_DEPTH_IMAGE_PIXEL` structs with a depth prop that provides the full depth range in mm.

**Comment by mkostin** [comment]
Thanks for feedback, glad that this has been resolved. Could you please specify what was the way you used before to get depth data that appeared clamped, was it `KinectGetDepthFrame`?

**Comment by bgstaal** [comment]
Yes, It was `KinectGetDepthFrame`. It seems ofxKinectCommonBridge is using an older version of KinectCommonBridge where `KinectGetDepthImagePixels` isn't available.

**Comment by IanByun** [comment]
> Yes, It was `KinectGetDepthFrame`. It seems ofxKinectCommonBridge is using an older version of KinectCommonBridge where `KinectGetDepthImagePixels` isn't available.

changing from
`KinectGetDepthFrame(hKinect, depthFormat.cbBufferSize, (BYTE*)depthPixelsRawBack.getPixels(), &timestamp))`
to
`KinectGetDepthImagePixels(hKinect, depthFormat.dwWidth*depthFormat.dwHeight, depthPixelsNui, &timestamp))`
actually solved the problem. Thanks!
